### ISSUE TITLE
ImportError: No module named frozen_version on nightly build

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#2283]
I grabbed the nightly build last night and upon startup got this error in the console. I'm on OS 10.10.5. LMK if I've omitted key information!

9/2/16 6:29:12.705 AM CellProfiler[48578]: Traceback (most recent call last):
9/2/16 6:29:12.705 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/**boot**.py", line 81, in <module>
9/2/16 6:29:12.705 AM CellProfiler[48578]:     _run()
9/2/16 6:29:12.705 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/__boot__.py", line 62, in _run
9/2/16 6:29:12.705 AM CellProfiler[48578]:     exec(compile(source, path, 'exec'), globals(), globals())
9/2/16 6:29:12.705 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/CellProfiler.py", line 1, in <module>
9/2/16 6:29:12.706 AM CellProfiler[48578]:     import cellprofiler.__main__
9/2/16 6:29:12.706 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/lib/python2.7/cellprofiler/**main**.py", line 5, in <module>
9/2/16 6:29:12.706 AM CellProfiler[48578]:     import cellprofiler.pipeline
9/2/16 6:29:12.706 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/lib/python2.7/cellprofiler/pipeline.py", line 48, in <module>
9/2/16 6:29:12.706 AM CellProfiler[48578]:     import cellprofiler.utilities.version as cpversion
9/2/16 6:29:12.706 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/version.py", line 126, in <module>
9/2/16 6:29:12.706 AM CellProfiler[48578]:     version_string = get_version()
9/2/16 6:29:12.706 AM CellProfiler[48578]:   File "/Applications/CellProfiler_2016_09_01.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/version.py", line 97, in get_version
9/2/16 6:29:12.706 AM CellProfiler[48578]:     import cellprofiler.frozen_version
9/2/16 6:29:12.706 AM CellProfiler[48578]: ImportError: No module named frozen_version
9/2/16 6:29:12.839 AM CellProfiler[48578]: CellProfiler Error
9/2/16 6:29:12.839 AM CellProfiler[48578]: 2016-09-02 06:29:12.838 CellProfiler[48578:4628646] CellProfiler Error

**Comment by AnneCarpenter** [comment]
Beta version from Apr 18 starts up just fine on my laptop under the same conditions.

**Comment by 0x00b1** [comment]
ha

**Comment by 0x00b1** [comment]
Thanks, @AnneCarpenter. I’ll investigate.

**Comment by AnneCarpenter** [comment]
Happy to test more versions if you point me in the right direction when you're ready!

**Comment by AnneCarpenter** [comment]
Still true as of the version I just downloaded today. I'm not sure how to report *which* nightly it is I got from the site because it doesn't seem any date or version number is user visible. LMK if more info would help!

**Comment by dlogan** [comment]
Mac nightly (downloaded today) still crashes.

```
11/17/16 1:12:09.756 PM CellProfiler[48938]: Traceback (most recent call last):
11/17/16 1:12:09.756 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/__boot__.py", line 81, in <module>
11/17/16 1:12:09.756 PM CellProfiler[48938]:     _run()
11/17/16 1:12:09.756 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/__boot__.py", line 62, in _run
11/17/16 1:12:09.756 PM CellProfiler[48938]:     exec(compile(source, path, 'exec'), globals(), globals())
11/17/16 1:12:09.756 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/CellProfiler.py", line 1, in <module>
11/17/16 1:12:09.757 PM CellProfiler[48938]:     import cellprofiler.__main__
11/17/16 1:12:09.757 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/lib/python2.7/cellprofiler/__main__.py", line 5, in <module>
11/17/16 1:12:09.757 PM CellProfiler[48938]:     import cellprofiler.pipeline
11/17/16 1:12:09.757 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/lib/python2.7/cellprofiler/pipeline.py", line 48, in <module>
11/17/16 1:12:09.757 PM CellProfiler[48938]:     import cellprofiler.utilities.version as cpversion
11/17/16 1:12:09.757 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/version.py", line 126, in <module>
11/17/16 1:12:09.757 PM CellProfiler[48938]:     version_string = get_version()
11/17/16 1:12:09.757 PM CellProfiler[48938]:   File "/Applications/CellProfiler - Nightly 20161117.app/Contents/Resources/lib/python2.7/cellprofiler/utilities/version.py", line 97, in get_version
11/17/16 1:12:09.757 PM CellProfiler[48938]:     import cellprofiler.frozen_version
11/17/16 1:12:09.757 PM CellProfiler[48938]: ImportError: No module named frozen_version
11/17/16 1:12:09.902 PM CellProfiler[48938]: CellProfiler Error
11/17/16 1:12:09.903 PM CellProfiler[48938]: 2016-11-17 13:12:09.902 CellProfiler[48938:1964812] CellProfiler Error
```

**Comment by c-scott** [comment]
The Mac nightly is still broken (on OS 10.11.6). I also checked out the latest build from git and I get the following error from the version module:

```
Traceback (most recent call last):
  File "/Users/systemsx/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/systemsx/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/systemsx/CellProfiler/cellprofiler/__main__.py", line 726, in <module>
    main()
  File "/Users/systemsx/CellProfiler/cellprofiler/__main__.py", line 143, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/app.py", line 21, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8631, in __init__
    self._BootstrapApp()
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/app.py", line 24, in OnInit
    import cellprofiler.gui.cpframe
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/cpframe.py", line 28, in <module>
    import cellprofiler.utilities.version
ImportError: No module named version
```

**Comment by jhung0** [comment]
Are you sure you have all requirements installed? Does CellProfiler work
for you?

**Comment by c-scott** [comment]
The 2.30 beta build from April works fine, as does the older pre-built binary (version 2.1?) I routinely use on this machine. I haven't built CellProfiler myself before but I followed this instructions here: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29 and everything appears to have installed and then built correctly. 

Given [this commit](https://github.com/CellProfiler/CellProfiler/pull/2265/commits/95ef4184300383f77815d133a76065e9f9541027) which removed the module cellprofilier is trying to call I assume the problem is something with this 'version' module in the current master, but if you have another suggestion on what may be the problem, I would be happy to try something out.

Here is the full output from trying to invoke cellprofiler in case there is a clue in there:
```
SystemsX:CellProfiler systemsx$ pythonw cellprofiler
MySQL could not be loaded.
Traceback (most recent call last):
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/modules/exporttodatabase.py", line 75, in <module>
    import MySQLdb
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: dlopen(/Users/systemsx/anaconda/lib/python2.7/site-packages/_mysql.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/systemsx/anaconda/lib/python2.7/site-packages/_mysql.so
  Reason: image not found
Traceback (most recent call last):
  File "/Users/systemsx/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/systemsx/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/systemsx/CellProfiler/cellprofiler/__main__.py", line 726, in <module>
    main()
  File "/Users/systemsx/CellProfiler/cellprofiler/__main__.py", line 143, in main
    app = cellprofiler.gui.app.App(0, workspace_path=workspace_path, pipeline_path=pipeline_path)
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/app.py", line 21, in __init__
    super(App, self).__init__(*args, **kwargs)
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8631, in __init__
    self._BootstrapApp()
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/app.py", line 24, in OnInit
    import cellprofiler.gui.cpframe
  File "/Users/systemsx/anaconda/lib/python2.7/site-packages/CellProfiler-3.0.0rc1-py2.7.egg/cellprofiler/gui/cpframe.py", line 28, in <module>
    import cellprofiler.utilities.version
ImportError: No module named version
```

**Comment by jhung0** [comment]
Maybe a wx issue because I don't think wx 3.0 is compatible.

**Comment by 0x00b1** [comment]
@c-scott It was a regression. 😞 Fixed by #2510.

**Comment by c-scott** [comment]
Thanks! Fetching #2510 fixed the problem. The OS X nightly still doesn't work, but at least I can use the version I built for now.

For your reference, I get this this error with the nightly (5 DEC 16):

```
05/12/2016 10:34:26.837 CellProfiler[1782]: Traceback (most recent call last):
05/12/2016 10:34:26.837 CellProfiler[1782]:   File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/__boot__.py", line 81, in <module>
05/12/2016 10:34:26.837 CellProfiler[1782]:     _run()
05/12/2016 10:34:26.837 CellProfiler[1782]:   File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/__boot__.py", line 62, in _run
05/12/2016 10:34:26.837 CellProfiler[1782]:     exec(compile(source, path, 'exec'), globals(), globals())
05/12/2016 10:34:26.837 CellProfiler[1782]:   File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/CellProfiler.py", line 1, in <module>
05/12/2016 10:34:26.837 CellProfiler[1782]:     import cellprofiler.__main__
05/12/2016 10:34:26.837 CellProfiler[1782]:   File "/Volumes/CellProfiler/CellProfiler.app/Contents/Resources/lib/python2.7/cellprofiler/__init__.py", line 8, in <module>
05/12/2016 10:34:26.837 CellProfiler[1782]:     __version__ = pkg_resources.get_distribution("cellprofiler").version
05/12/2016 10:34:26.838 CellProfiler[1782]:   File "pkg_resources/__init__.pyc", line 561, in get_distribution
05/12/2016 10:34:26.838 CellProfiler[1782]:   File "pkg_resources/__init__.pyc", line 441, in get_provider
05/12/2016 10:34:26.838 CellProfiler[1782]:   File "pkg_resources/__init__.pyc", line 962, in require
05/12/2016 10:34:26.838 CellProfiler[1782]:   File "pkg_resources/__init__.pyc", line 849, in resolve
05/12/2016 10:34:26.838 CellProfiler[1782]: pkg_resources.DistributionNotFound: The 'cellprofiler' distribution was not found and is required by the application
05/12/2016 10:34:26.970 CellProfiler[1782]: CellProfiler Error
05/12/2016 10:34:26.970 CellProfiler[1782]: 2016-12-05 10:34:26.969 CellProfiler[1782:23374] CellProfiler Error
```

![screen shot 2016-12-05 at 10 34 32](https://cloud.githubusercontent.com/assets/24315101/20880053/acee1972-bad6-11e6-8987-2c36547e754d.png)

**Comment by dlogan** [comment]
Yeah, I just tried the Mac Nightly build and got the same error.   Same as https://github.com/CellProfiler/CellProfiler/issues/2494

**Comment by mcquin** [comment]
Mac nightlies should be working now.
