### ISSUE TITLE
Hitting cancel on the nightly doesn't kill the pipeline

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler#2896]
As of today's nightly (not sure exact commit but somewhere around 66421a840f96604d82442f9132247eab52b8e456), hitting 'Cancel' after encountering an error in the prebuilt or source versions of CellProfiler does not kill CP, just skips that image and goes to the next.  Previous behavior was to kill CP so the user could go in and fix the error.

**Comment by 0x00b1** [comment]
Fixed. @bethac07 Would you mind verifying with the latest nightly?

**Comment by bethac07** [comment]
I don't know if nightly vs source matters, but I just pulled the most recent master commit (5cb99e616f630490d4cd35208f580484648a202d) and it's still broken.  If I need a compiled one, where would I find one that's up to date?

**Comment by bethac07** [comment]
Confirmed that it's still broken in the beta from just now.

**Comment by bethac07** [comment]
Yes!
