### ISSUE TITLE
Cellprofiler - Cellpose

### ISSUE THREAD

**Issue by MathiasBeller** [CellProfiler/CellProfiler#4523]
Hi, 

I am installing CellProfiler from source (version 4.2.1) on a Windows 10 machine (Windows 10 enterprise 2016 LTSB) and want to include also Cellpose (I tried Cellpose versions 1.02 as well as 0.6) with GPU support. During the install, I am running into an issue that the numpy version required by Cellprofiler is in conflict with the numpy version accepted by Cellpose, which is limited by compatibility with the Numba library. I fixed this manually by forcing certain package versions and installing the dependencies one after the other, which turned out to let everything run (numpy==1.22.3 and numba==0.53.0). 

While Cellprofiler starts, there is a warning message on the console ("Python rejected the system locale detected by WX ('en_GB').
This shouldn't cause problems, but please let us know if you encounter errors."). When I am running basic operations in Cellprofiler (e.g. Gaussian Filter), this works and the results are displayed as expected. However, when I use Cellpose an error occurs at the end of the operation ("norm = matplotlib.colors.Normalize(vmin=0, vmax=orig_image_max) UnboundLocalError: local variable 'orig_image_max' referenced before assignment") and the execution stops (in GPU as well as CPU mode). Any ideas how this could be solved? Any help would be highly appreciated!

Thank you very much in advance! 
Best, Mathias

**Comment by bethac07** [comment]
Apologies! It looks like in #4510 where we fixed some things with color mapping, something there broke. The team will look into it. 

You could hop back a couple of commits to cd728946b160c301bdeb4fd0e41c28b86651ea85 while we take a look; otherwise, you could turn display off, but that's obviously not as ideal.

**Comment by MathiasBeller** [comment]
Dear Beth, thank you so much for the quick reply! I will check an earlier commit, All the best, Mathias

**Comment by MathiasBeller** [comment]
I used now the build version you mentioned, but still get the same error ("...norm = matplotlib.colors.Normalize(vmin=0, vmax=orig_image_max) UnboundLocalError: local variable 'orig_image_max' referenced before assignment...").

**Comment by bethac07** [comment]
If you do `git log | head`, you should be able to see the last commit where you're currently checked out; `orig_image_max` wasn't added until after the commit message I posted, so it shouldn't be possible for it to be there in that commit, so something funny is happening.

In any case, I think this should be fixed by #4516 , which I just pulled.

**Comment by MathiasBeller** [comment]
With the latest commit everything works again like a charm! Thank you so much for your lightning-fast help!
