### ISSUE TITLE
Improve resolution of GUI, for retina displays

### ISSUE THREAD

**Issue by AnneCarpenter** [CellProfiler/CellProfiler#472]
The GUI is pixelated compared to other application on new Mac retina displays.

**Comment by 0x00B1** [comment]
This was resolved by upgrading to wxPython 3.0.

**Comment by swvanderlaan** [comment]
Actually, for me this is not resolved. I have installed CellProfiler as per instructions here: https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29. And my `brew config` shows this: 

```
HOMEBREW_VERSION: 1.9.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 23b20f82c77e001299cb393525c914434e41340a
Core tap last commit: 25 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/swvanderlaan/Library/Logs/Homebrew
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 1.8.0_201, 1.8.0_172
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

Yet, my CellProfiler GUI is still pixelated. I have a MacBook (Retina, 12-inch, Early 2016) with macOS Mojave version 10.14.2.
